### PR TITLE
Regenerate manifest.json when config/manifest.js is changed

### LINKED ISSUE #48: Regenerate manifest.json when config/manifest.js is changed
See discussion in #47

### PR DESCRIPTION
**Pull request by simonihmig**
Closes #48

@san650 Finally found some time to work on this. This is fully functional! 

However I had to skip the broccoli test  (`node-tests/broccoli/generate-manifest-json-test.js`) because I am not sure how to make this testable again. Or if this is actually needed...

This is because the Broccoli plugin now does much more, as it has to generate the manifest by itself, rather than getting the data from `index.js`. Because it has to regenerate it upon change, while the hooks in `index.js` are only invoked once. So currently it has access to the ember-cli `project` model, and with that dependency testing becomes harder. Would probably have to mock all relevant `project` methods to make this testable. 

Not sure if that is really worth the needed effort, as the acceptance tests still cover the overall functionality. Your thoughts?

### CODE REVIEW

**Comment by simonihmig** [comment]
@san650 ping :)

**Comment by san650** [comment]
Hi @simonihmig let's delete the broccoli test, that's fine. As you said, acceptance test are already covering everything. :)

Do you need my help/assistance with anything else? More than glad to help. Let me know when you think this is ready to merge!

**Comment by simonihmig** [comment]
@san650 deleted it (and replaced .jshintrc file for .eslintrc). This should be ready to be merged then. You might want to try this out before maybe, to make sure it works as expected. But it was for me...

**Comment by san650** [comment]
Thanks @simonihmig

**Comment by san650** [comment]
@simonihmig One of the problems I found with this PR (is not working well) is that the addon relies on another addon `ember-web-app-rename` to rename the manifest file -- to whatever name the user wants to use -- after the manifest is generated and processed by broccoli-asset-rev addon.

This process makes code reload hard because changing manifest.js file triggers the rebuild of ember-web-app but not the build of `ember-web-app-rename` 😞 

Said that, this feature (renaming) was causing more problems than adding real benefits so I'm dropping it and plan to release a major version with this breaking change soon.

After this breaking change is released, I'll come back to this PR, update it to the latest version and merge it. Sorry for the delay and appreciate your help in making the addon better and better!

**Comment by simonihmig** [comment]
@san650 Just rebased this and fixed the conflicts.

Indeed I missed the `ember-web-app-rename` thing. I tested this with the addon's dummy app, and a simple `manifest.js` I created for this. But this was not using the other rename addon. Now that the latter is gone, this should hopefully work as expected now!

**Pull request merged**
