### PR TITLE
Revert "Rename  manifest.json to manifest.ember-web-app.json during build"

### PR DESCRIPTION
**Pull request by teddyzeenny**
This reverts commit 1bd4acb532c2a106b6b2768ad92ef8c1a4f4a498.

Broccoli throws an error on rebuilds when a file is renamed in `postBuild`.

I don't have a clear idea on how to fix that and I'm a bit short on time at the moment.

### CODE REVIEW

**Comment by san650** [comment]
Let's change the name of the manifest file for now to be `manifest.ember-web-app.json`. I can tackle the issue if you don't have time

**Comment by san650** [comment]
I'll close this PR in favor of #25

**Comment by san650** [comment]
@teddyzeenny I've published a new patch version which removes the `postBuild` step. See https://github.com/san650/ember-web-app/releases/tag/v1.0.5.

Thank you for taking the time for reporting the issue and trying to fix it!

**Comment by teddyzeenny** [comment]
Thanks @san650! Haven't had the time to work on it or try it today, I may have some time tomorrow. Will let you know as soon as I test it.

**Comment by san650** [comment]
@teddyzeenny can you share the error message? I'm trying this now and I don't see an error message on rebuilds. How are you reproducing the error? Is it related to fastboot?

**Pull request closed without merging**
